project_id = "quchpmkxhfftjdlmkhkd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

[edge_runtime]
enabled = true
port = 54329

[analytics]
enabled = false

[functions.categorize-entry]
verify_jwt = true

[functions.generate-insights]
verify_jwt = true